from DoubleLinkedList import *
miLista=DoubleLinkedList()
miLista.agregar_al_inicio(50)
miLista.agregar_al_final(60)
miLista.agregar_al_final(65)
miLista.agregar_al_final(70)
miLista.agregar_al_final(80)
miLista.agregar_al_final(90)
miLista.transversal(1)
miLista.eliminar(2)
miLista.transversal(1)
miLista.actualizar(80,88)
miLista.transversal(1)
print("Posicion de 80:")
miLista.buscar(80)
